---
# Tasks for handling CLI customization and publishing

# - name: "ensure nginx directory for cli exists"
#   file:
#     path: "{{ cli.nginxdir }}"
#     state: directory
#   become: "{{ cli.dir.become }}"

#- include: docker_login.yml

#
#  If you're copying from local, the 'src' item will likely default to
#  '$OPENWHISK_HOME/../incubator-openwhisk-cli/release/OpenWhisk_CLI-latest-all.tgz'
#
- name: "Configure for remote retreival"
  set_fact:
    cli_archive_src: "{{ openwhisk_cli.remote.location }}/{{ openwhisk_cli.remote.name}}-{{ openwhisk_cli.tag }}-all.tgx"
  when: openwhisk_cli.installation_mode == "remote"

- name: "Configure for local retreival"
  set_fact:
    cli_archive_src: "{{ openwhisk_cli_home }}/{{ openwhisk_cli.archive_name}}-{{ openwhisk_cli.tag }}-all.tgx"
  when: openwhisk_cli.installation_mode == "local"

- name: "expand the binaries archive into the Nginx directory"
  unarchive:
      src: "{{ cli_archive_src }}"
      dest: "{{ openwhisk_cli.nginxdir }}"
      mode: '0644'
      validate_certs: yes
  when: openwhisk_cli.installation_mode == "remote"

- name: "get a list of archives to expand"
  find:
      paths: "{{ openwhisk_cli.nginxdir }}"
      patterns:
          - '*.tgz'
          - '*.zip'
      recurse: true
  register: archives

- name: "print find results"
  debug:
      var: archives

- include: download_cli.yml
  when: openwhisk_cli.installation_mode == "remote"
